export type Locale = "ar" | "en";

export const customerTypeOptions = {
  ar: ["بقالة", "سوبرماركت", "موزع", "مطعم", "فرد"],
  en: ["Grocery", "Supermarket", "Distributor", "Restaurant", "Individual"],
};

export const company = {
  legalNameAr: "مؤسسة برغندي للأغذية",
  legalNameEn: "Burgundy Foods Establishment",
  brandName: "Burgundy Foods",
  activityAr: "تجارة وتوزيع المواد الغذائية",
  activityEn: "Food Trading & Distribution",
  cityAr: "الرياض، المملكة العربية السعودية",
  cityEn: "Riyadh, Kingdom of Saudi Arabia",
  email: "info@burgundy-foods.com",
  website: "www.burgundy-foods.com",
  nationalNumber: "7052343444",
  social: "@burgundyfoods",
} as const;

export const copy = {
  ar: {
    nav: {
      brand: company.brandName,
      factory: company.activityAr,
      home: "الرئيسية",
      about: "عن الشركة",
      products: "المنتجات",
      wholesale: "الجملة والتوزيع",
      quote: "طلب عرض سعر",
      contact: "تواصل معنا",
      dashboard: "لوحة التحكم",
      signIn: "تسجيل الدخول",
      signOut: "تسجيل خروج",
      language: "EN",
      themeLight: "نهاري",
      themeDark: "ليلي",
    },
    home: {
      kicker: "Premium Food Distribution",
      title: company.brandName,
      lead: "مؤسسة برغندي للأغذية شركة سعودية لتجارة وتوزيع المواد الغذائية من الرياض، نوفر منتجات غذائية عالية الجودة—من ضمنها منتجات الباستا الفاخرة—للموزعين والسوبرماركت ومنشآت قطاع الضيافة.",
      primary: "اطلب عرض سعر",
      secondary: "تصفح المنتجات",
      badges: ["مستوردون معتمدون", "جودة عالية", "خدمة الجملة"],
      highlights: [
        ["هوية تجارية موثوقة", "مؤسسة برغندي للأغذية مسجلة في المملكة العربية السعودية برقم وطني موحد ومقر تشغيلي في الرياض."],
        ["تشكيلة منتجات منتقاة", "نختار منتجات غذائية فاخرة بمواصفات واضحة وعبوات احترافية جاهزة للرف."],
        ["جاهزية للجملة", "مناسبة للموزعين والسوبرماركت ومنشآت الضيافة داخل المملكة العربية السعودية."],
      ],
      orderKicker: "من الرف إلى الطلب",
      orderTitle: "تجربة طلب مصممة لقطاع الجملة.",
      orderLead: "اختر المنتج، راجع بيانات العبوة، ثم أرسل عدد الكراتين المطلوبة. يراجع فريق المبيعات السعر والتوفر قبل اعتماد الطلب.",
      orderSteps: ["اختيار الصنف", "تحديد الكراتين", "إرسال بيانات المنشأة", "تأكيد السعر والتوفر"],
      platformKicker: "تشغيل المؤسسة",
      platformTitle: "موقع عام ولوحة إدارة لتشغيل عمليات التوزيع.",
      platformLead: "تعرض الواجهة هوية Burgundy Foods ومنتجاتها، بينما تدعم لوحة التحكم إدارة الأصناف والعملاء وطلبات عروض الأسعار والمخزون.",
      adminLabel: "قسم إداري",
      areas: ["المنتجات", "العملاء", "الطلبات", "المخزون"],
    },
    about: {
      kicker: "عن Burgundy Foods",
      title: "مؤسسة سعودية لتجارة وتوزيع المنتجات الغذائية.",
      lead: "تأسست Burgundy Foods في الرياض لخدمة قطاع التجزئة والجملة بمنتجات غذائية مستوردة وموزعة بمعايير عالية. نركز على إتاحة منتجات بمواصفات واضحة وعبوات احترافية تخدم الموزعين والسوبرماركت ومنشآت قطاع الضيافة.",
      cards: [
        ["حضور مميز على الرف", "نوفر منتجات بهوية بصرية واضحة وعبوات تجذب المستهلك داخل نقطة البيع."],
        ["تشكيلة فاخرة", "نختار منتجات منتقاة من ضمنها الباستا الفاخرة بمواصفات غذائية محددة."],
        ["مسار جملة احترافي", "مصمم للكميات التجارية من اختيار المنتج إلى تأكيد السعر والتوفر."],
        ["جاهزية للتوسع", "لوحة تحكم لإدارة الأصناف والعملاء والطلبات والمخزون وتقارير الأداء."],
      ],
    },
    products: {
      kicker: "منتجاتنا",
      title: "Burgundy Foods Pasta Collection",
      lead: "منتجات مكرونة عالية الجودة للتجزئة والجملة وقطاع الأغذية",
      quoteCta: "اطلب عرض سعر للمنتجات",
      empty: "لا توجد منتجات بعد. يمكنك إضافة منتجات من لوحة التحكم.",
      weight: "الوزن",
      packs: "عدد العبوات بالكرتون",
      barcode: "باركود",
      unavailable: "غير متوفر",
      origin: "المنشأ",
      order: "اطلب هذا المنتج",
      howTitle: "كيف يكتمل طلب الجملة؟",
      howLead: "اختر الصنف، راجع بيانات العبوة، ثم اكتب عدد الكراتين في نموذج عرض السعر. يصل الطلب للإدارة لمراجعة السعر والمخزون.",
    },
    wholesale: {
      kicker: "الجملة والتوزيع",
      title: "حلول توريد لقطاع التجزئة والجملة في المملكة.",
      lead: "نخدم الموزعين والسوبرماركت ومنشآت قطاع الضيافة بكميات تجارية وبشروط واضحة. اطلب عرض سعر لتحصل على بيانات الأسعار والتوفر.",
      points: [
        ["موزعون ومستوردون", "تجهيز الكميات الكبيرة بأسعار جملة وشروط واضحة."],
        ["سوبرماركت وبقالات", "حضور رف قوي بمنتجات غذائية فاخرة مغلفة باحتراف."],
        ["مطاعم وفنادق", "توريد منتظم بجودة ثابتة لخدمة قطاع الضيافة."],
      ],
    },
    quote: {
      kicker: "طلب عرض سعر",
      title: `أرسل كميات ${company.brandName} المطلوبة.`,
      lead: "اختر المنتجات واكتب عدد الكراتين لكل صنف. سنراجع المخزون والسعر ثم نتواصل معك لتأكيد الطلب.",
      serviceTitle: "مصمم للموزعين والكميات التجارية.",
      serviceLead: "طلبات عروض الأسعار تظهر في لوحة التحكم ليتم تحويلها إلى طلب داخلي بعد موافقة المبيعات.",
      guide: ["اختر المنتج", "أدخل عدد الكراتين", "أرسل بيانات المنشأة", "انتظر تأكيد السعر والتوفر"],
    },
    contact: {
      kicker: "تواصل معنا",
      title: `جاهزون لخدمة طلبات ${company.brandName}.`,
      lead: "للاستفسارات التجارية وطلبات التوريد والجملة وفرص التوزيع، تواصل معنا عبر البريد الرسمي.",
      whatsapp: "واتساب",
      email: "البريد الإلكتروني",
      address: "العنوان",
    },
    forms: {
      customerName: "اسم العميل",
      companyName: "اسم المنشأة",
      city: "المدينة",
      phone: "رقم الجوال",
      email: "البريد الإلكتروني",
      customerType: "نوع العميل",
      requestedProducts: "المنتجات المطلوبة",
      cartonQty: "عدد الكراتين",
      notes: "ملاحظات إضافية",
      sendQuote: "إرسال طلب العرض",
      sending: "جاري الإرسال...",
      chooseProducts: "يرجى اختيار المنتجات والكميات المطلوبة.",
      quoteSuccess: "تم إرسال طلب عرض السعر بنجاح، سيتواصل معك فريق المبيعات قريبًا.",
      formError: "حدث خطأ أثناء الإرسال، حاول مرة أخرى لاحقًا.",
      name: "الاسم",
      message: "الرسالة",
      sendMessage: "أرسل الرسالة",
      contactSuccess: "تم إرسال رسالتك بنجاح، سنعود إليك قريبًا.",
      noProducts: "لا توجد منتجات حاليًا. تواصل معنا وسنساعدك مباشرة.",
    },
    auth: {
      title: "تسجيل دخول لوحة التحكم",
      lead: "استخدم بريد المدير أو الموظف وكلمة المرور للوصول إلى لوحة الإدارة.",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      error: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      loading: "جاري تسجيل الدخول...",
      submit: "تسجيل الدخول",
      help: "إذا لم تكن لديك بيانات دخول، يمكنك إنشاء أول مستخدم عبر قاعدة البيانات المحلية.",
    },
    dashboard: {
      kicker: "لوحة التحكم",
      title: `مرحبًا بك في إدارة ${company.brandName}`,
      lead: "تحكم في المنتجات والعملاء والطلبات والمخزون والتقارير الأساسية من هنا.",
      back: "العودة إلى الموقع",
      signOut: "تسجيل الخروج",
      links: [
        "الرئيسية",
        "المنتجات",
        "العملاء",
        "الموردون",
        "المشتريات",
        "المخزون",
        "عروض الأسعار",
        "أوامر البيع",
        "سندات التسليم",
        "الفواتير",
        "المقبوضات والمدفوعات",
        "المحاسبة",
        "التقارير",
        "إعدادات الشركة",
      ],
    },
    footer: {
      legalName: company.legalNameAr,
      activity: company.activityAr,
      city: company.cityAr,
      description:
        "مؤسسة Burgundy Foods هي مؤسسة سعودية لتجارة وتوزيع المواد الغذائية مقرها الرياض، وتركز على منتجات المكرونة والمواد الغذائية عالية الجودة لقطاع التجزئة والجملة وخدمات الأغذية.",
      quickLinksHeading: "روابط سريعة",
      contactHeading: "تواصل معنا",
      emailLabel: "البريد الإلكتروني",
      websiteLabel: "الموقع الإلكتروني",
      addressLabel: "العنوان",
      nationalNumberLabel: "الرقم الوطني الموحد",
      rights: "جميع الحقوق محفوظة.",
    },
  },
  en: {
    nav: {
      brand: company.brandName,
      factory: company.activityEn,
      home: "Home",
      about: "About",
      products: "Products",
      wholesale: "Wholesale & Distribution",
      quote: "Request quote",
      contact: "Contact",
      dashboard: "Dashboard",
      signIn: "Sign in",
      signOut: "Sign out",
      language: "AR",
      themeLight: "Light",
      themeDark: "Dark",
    },
    home: {
      kicker: "Premium Food Distribution",
      title: company.brandName,
      lead: "Burgundy Foods Establishment is a Saudi food trading and distribution company based in Riyadh. We import, supply, and distribute high-quality food products — including premium pasta — to retailers, wholesalers, supermarkets, and food service businesses.",
      primary: "Request a quote",
      secondary: "Browse products",
      badges: ["Trusted importer", "Premium quality", "Wholesale ready"],
      highlights: [
        ["Registered Saudi entity", "Burgundy Foods Establishment is registered in the Kingdom with a unified national number and operations in Riyadh."],
        ["Curated product range", "We select premium food products with clear specifications and shelf-ready packaging."],
        ["Wholesale ready", "Built for distributors, supermarkets, and food service businesses across Saudi Arabia."],
      ],
      orderKicker: "Shelf to order",
      orderTitle: "An ordering experience built for wholesale.",
      orderLead: "Choose a product, review pack data, then submit carton quantities. Sales reviews price and stock before approving the order.",
      orderSteps: ["Choose product", "Enter cartons", "Submit company details", "Confirm price and stock"],
      platformKicker: "Distribution operations",
      platformTitle: "Public storefront with an operational dashboard.",
      platformLead: "The storefront presents Burgundy Foods and its product range while the dashboard manages SKUs, customers, quote requests, and inventory.",
      adminLabel: "Admin section",
      areas: ["Products", "Customers", "Orders", "Inventory"],
    },
    about: {
      kicker: "About Burgundy Foods",
      title: "A Saudi food trading and distribution establishment.",
      lead: "Burgundy Foods was founded in Riyadh to serve the Saudi retail and wholesale market with imported and distributed food products held to high standards. We focus on products with clear specifications and professional packaging for distributors, supermarkets, and food service businesses.",
      cards: [
        ["Strong shelf presence", "Products with a clear visual identity and packaging that performs at the point of sale."],
        ["Premium selection", "A curated assortment including premium pasta products with defined nutritional specifications."],
        ["Wholesale workflow", "Designed for trade quantities, from product selection through price and stock confirmation."],
        ["Ready to scale", "Dashboard for managing SKUs, customers, orders, inventory, and core reports."],
      ],
    },
    products: {
      kicker: "Products",
      title: "Burgundy Foods Pasta Collection",
      lead: "Premium pasta products for retail, wholesale, and food service distribution",
      quoteCta: "Request a quote",
      empty: "No products yet. Add products from the dashboard.",
      weight: "Weight",
      packs: "Packs per carton",
      barcode: "Barcode",
      unavailable: "Not available",
      origin: "Origin",
      order: "Request this product",
      howTitle: "How does a wholesale request work?",
      howLead: "Choose a product, review its pack data, then enter carton quantities in the quote form. The request reaches management for price and stock review.",
    },
    wholesale: {
      kicker: "Wholesale & Distribution",
      title: "Supply solutions for the Saudi retail and wholesale market.",
      lead: "We supply distributors, supermarkets, and food service businesses with trade quantities under clear commercial terms. Request a quote to receive pricing and availability.",
      points: [
        ["Distributors & importers", "Bulk fulfilment at wholesale pricing with clear terms."],
        ["Supermarkets & groceries", "Strong shelf presence with professionally packaged premium food products."],
        ["Restaurants & hotels", "Reliable supply with consistent quality for the food service sector."],
      ],
    },
    quote: {
      kicker: "Quote request",
      title: `Send your ${company.brandName} quantities.`,
      lead: "Select products and enter carton quantities. We will review stock and pricing, then contact you to confirm.",
      serviceTitle: "Designed for distributors and trade buyers.",
      serviceLead: "Customer quote requests appear in the dashboard so sales can approve and convert them into internal orders.",
      guide: ["Choose product", "Enter cartons", "Submit company details", "Wait for price and stock confirmation"],
    },
    contact: {
      kicker: "Contact",
      title: `Ready to support ${company.brandName} requests.`,
      lead: "For business inquiries, product supply, wholesale requests, and distribution opportunities, please reach us at the official email.",
      whatsapp: "WhatsApp",
      email: "Email",
      address: "Address",
    },
    forms: {
      customerName: "Customer name",
      companyName: "Company name",
      city: "City",
      phone: "Mobile number",
      email: "Email",
      customerType: "Customer type",
      requestedProducts: "Requested products",
      cartonQty: "Cartons",
      notes: "Additional notes",
      sendQuote: "Submit quote request",
      sending: "Sending...",
      chooseProducts: "Please choose products and quantities.",
      quoteSuccess: "Your quote request was sent successfully. Sales will contact you soon.",
      formError: "Something went wrong. Please try again later.",
      name: "Name",
      message: "Message",
      sendMessage: "Send message",
      contactSuccess: "Your message was sent successfully. We will get back to you soon.",
      noProducts: "No products are available right now. Contact us and we will help directly.",
    },
    auth: {
      title: "Dashboard sign in",
      lead: "Use an admin or employee email and password to access the management dashboard.",
      email: "Email",
      password: "Password",
      error: "Email or password is incorrect.",
      loading: "Signing in...",
      submit: "Sign in",
      help: "If you do not have credentials, create the first user through the local database seed.",
    },
    dashboard: {
      kicker: "Dashboard",
      title: `Welcome to ${company.brandName} management`,
      lead: "Manage products, customers, orders, inventory, and core reports from here.",
      back: "Back to website",
      signOut: "Sign out",
      links: [
        "Overview",
        "Products",
        "Customers",
        "Suppliers",
        "Purchases",
        "Inventory",
        "Quotations",
        "Sales Orders",
        "Delivery Notes",
        "Invoices",
        "Payments",
        "Finance",
        "Reports",
        "Company settings",
      ],
    },
    footer: {
      legalName: company.legalNameEn,
      activity: company.activityEn,
      city: company.cityEn,
      description:
        "Burgundy Foods is a Saudi food trading and distribution establishment based in Riyadh, focused on premium pasta and food products for retail, wholesale, and food service distribution.",
      quickLinksHeading: "Quick Links",
      contactHeading: "Contact",
      emailLabel: "Email",
      websiteLabel: "Website",
      addressLabel: "Address",
      nationalNumberLabel: "National Number",
      rights: "All rights reserved.",
    },
  },
} as const;

export function getCopy(locale: Locale) {
  return copy[locale];
}
